build:
	sudo docker build --tag tbutzer:gdalt .

run:
	sudo docker run --rm -it \
		-v /home/ubuntu:/data \
		--name gdalt tbutzer:gdalt /bin/bash
build18:
	sudo docker build -f Dockerfile.18 --tag tbutzer:gdalt18 .
run18:
	sudo docker run --rm -it \
		-v /home/ubuntu:/data \
		--name gdalt18 tbutzer:gdalt18 /bin/bash
